CREATE SCHEMA RAW_DATA;

CREATE TABLE RAW_DATA.SNIFIM (
    STORE_ID INT,
    BIKORET_NO INT,
    STORE_TYPE INT,
    STORE_NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    ZIP_CODE VARCHAR(20)
);